// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: pkg/grpclib/test/proto_test.proto

package test

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestName        string `protobuf:"bytes,1,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	TestDescription string `protobuf:"bytes,2,opt,name=test_description,json=testDescription,proto3" json:"test_description,omitempty"`
}

func (x *UnitTestRequest) Reset() {
	*x = UnitTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpclib_test_proto_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitTestRequest) ProtoMessage() {}

func (x *UnitTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpclib_test_proto_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitTestRequest.ProtoReflect.Descriptor instead.
func (*UnitTestRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpclib_test_proto_test_proto_rawDescGZIP(), []int{0}
}

func (x *UnitTestRequest) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *UnitTestRequest) GetTestDescription() string {
	if x != nil {
		return x.TestDescription
	}
	return ""
}

type UnitTestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UnitTestResponse) Reset() {
	*x = UnitTestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpclib_test_proto_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitTestResponse) ProtoMessage() {}

func (x *UnitTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpclib_test_proto_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitTestResponse.ProtoReflect.Descriptor instead.
func (*UnitTestResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpclib_test_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *UnitTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnitTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_grpclib_test_proto_test_proto protoreflect.FileDescriptor

var file_pkg_grpclib_test_proto_test_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6c, 0x69, 0x62, 0x2f, 0x74, 0x65,
	0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0f, 0x55,
	0x6e, 0x69, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x65, 0x73, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x55,
	0x0a, 0x0f, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x42, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x64, 0x72, 0x6f, 0x6c, 0x61, 0x69, 0x6e, 0x2f, 0x67,
	0x6f, 0x6d, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x6c, 0x69,
	0x62, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpclib_test_proto_test_proto_rawDescOnce sync.Once
	file_pkg_grpclib_test_proto_test_proto_rawDescData = file_pkg_grpclib_test_proto_test_proto_rawDesc
)

func file_pkg_grpclib_test_proto_test_proto_rawDescGZIP() []byte {
	file_pkg_grpclib_test_proto_test_proto_rawDescOnce.Do(func() {
		file_pkg_grpclib_test_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpclib_test_proto_test_proto_rawDescData)
	})
	return file_pkg_grpclib_test_proto_test_proto_rawDescData
}

var file_pkg_grpclib_test_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpclib_test_proto_test_proto_goTypes = []interface{}{
	(*UnitTestRequest)(nil),  // 0: prototest.UnitTestRequest
	(*UnitTestResponse)(nil), // 1: prototest.UnitTestResponse
}
var file_pkg_grpclib_test_proto_test_proto_depIdxs = []int32{
	0, // 0: prototest.UnitTestService.RunTest:input_type -> prototest.UnitTestRequest
	1, // 1: prototest.UnitTestService.RunTest:output_type -> prototest.UnitTestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpclib_test_proto_test_proto_init() }
func file_pkg_grpclib_test_proto_test_proto_init() {
	if File_pkg_grpclib_test_proto_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpclib_test_proto_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpclib_test_proto_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitTestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpclib_test_proto_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpclib_test_proto_test_proto_goTypes,
		DependencyIndexes: file_pkg_grpclib_test_proto_test_proto_depIdxs,
		MessageInfos:      file_pkg_grpclib_test_proto_test_proto_msgTypes,
	}.Build()
	File_pkg_grpclib_test_proto_test_proto = out.File
	file_pkg_grpclib_test_proto_test_proto_rawDesc = nil
	file_pkg_grpclib_test_proto_test_proto_goTypes = nil
	file_pkg_grpclib_test_proto_test_proto_depIdxs = nil
}
